/**
 * Normalized coordinates (0–1) are relative to the source map image
 * (manifest.width × manifest.height), origin top-left, x right, y down.
 *
 * Leaflet CRS.Simple uses [y, x] with y increasing north. We invert y so
 * (0,0) is the top-left of the source image:
 *   leafletY = -(y * sourceHeight)
 *   leafletX = x * sourceWidth
 *
 * Tiles are generated by padding the source onto a
 * 2^maxNativeZoom * tileSize square without resampling the source pixels.
 * Padding sits on the bottom and right and must not be used as the 0–1 space.
 */
import type { MapCoordinate, MapManifest } from '@/types';

export function toLeaflet(coord: MapCoordinate, manifest: MapManifest): [number, number] {
  const leafletY = -(coord.y * manifest.height);
  const leafletX = coord.x * manifest.width;
  return [leafletY, leafletX];
}

export function fromLeaflet(
  latlng: { lat: number; lng: number },
  manifest: MapManifest,
): MapCoordinate {
  return {
    x: latlng.lng / manifest.width,
    y: -latlng.lat / manifest.height,
  };
}

export function paddedMapSize(manifest: MapManifest): number {
  return manifest.tileSize * 2 ** manifest.maxNativeZoom;
}

export function sourceBounds(manifest: MapManifest): [[number, number], [number, number]] {
  return [
    [-manifest.height, 0],
    [0, manifest.width],
  ];
}

export function isNormalized(coord: MapCoordinate): boolean {
  return coord.x >= 0 && coord.x <= 1 && coord.y >= 0 && coord.y <= 1;
}
